/**
 * @description       : 
 * @author            : António Vicente
 * @group             : 
 * @last modified on  : 2026-06-23
 * @last modified by  : António Vicente
 * Modifications Log
 * Ver   Date         Author            Modification
 * 1.0   2026-06-23   António Vicente   Initial Version
**/
public with sharing class GlobalConstants {
    // Standard Object Picklist API NAME
    public static final String CLOSED_WON_OPP = 'Closed Won';
    
}